### ISSUE TITLE
Please consider adding a link to my repo

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [yukixz/qqbot.py#6]
My repo: https://github.com/jqqqqqqqqqq/coolq-telegram-bot

I have fixed some bugs in cqsdk and added a new feature to use multiple function to handle same incoming event in a queue, like what python_telegram_bot did

Also, I added some other class to decode anonymous message or group member's info.

@JogleLew upgraded cqsdk to fit the newest version of socketapi.

We appreciate your amazing work in creating socketapi and we want to help maintaining cqsdk.

**Comment by yukixz** [comment]
Thanks. Seem someone have updated https://github.com/yukixz/cqsocketapi. Could you give me the latest repo that i can update readme of socketapi repo too.

**Comment by jqqqqqqqqqq** [comment]
I didn't make any change in socketapi. The new cqsdk is based on your latest cqsocketapi.

**Comment by yukixz** [comment]
OK, thanks for all.
